- hosts: [jenkins]
  become: yes
  become_method: sudo
  tasks:
  - name: Install nginx
    package: name=nginx state=latest update_cache=yes
    notify:
    - restart nginx
  - name: write configuration
    copy:
      src: index.html
      dest: /var/www/html/index.html
  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted
